version: "3.8"

services:
  localstack:
    # "${LOCALSTACK_DOCKER_NAME-localstack_main}" means docker-compose.yml will refer to the value of variable called LOCALSTACK_DOCKER_NAME in a .env file. Otherwise the docker container is named "localstack_main".  
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    # In case you need the full set of dependencies, the "localstack/localstack-full" image can be used instead
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro
      - "127.0.0.1:53:53/udp"            # only required for Pro
      - "127.0.0.1:443:443"              # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      # Specify the services in a variable named LOCALSTACK_SERVICES, otherwise localstack does not work...
      - SERVICES=${LOCALSTACK_SERVICES:-ssm,cloudwatch,cloudformation}
      - DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=${DEBUG:-1}
      - EDGE_PORT=${LOCALSTACK_EDGE_PORT:-4566}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR:-local}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_data:/var/lib/localstack" # Mounts the local directory to the container
      - "/var/run/docker.sock:/var/run/docker.sock" # Mounts the docker socket